# Generated by Django 4.0.1 on 2022-01-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('tempo_de_serviço', models.IntegerField(default=0)),
                ('remuneração', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
